version: 0.2

phases:
  install:
    commands:
      - echo Installing kubectl
      - curl -o kubectl https://s3.us-west-2.amazonaws.com/amazon-eks/1.27.0/2023-11-14/bin/linux/amd64/kubectl
      - chmod +x kubectl
      - mv kubectl /usr/local/bin/

  pre_build:
    commands:
      - echo Updating kubeconfig
      - aws eks update-kubeconfig --region us-east-1 --name brain-tasks-cluster-2

  build:
    commands:
      - echo Deploying application
      - kubectl apply -f deployment.yaml
      - kubectl apply -f service.yaml
      - kubectl get pods
      - kubectl get svc
